### ISSUE TITLE
Only enable in incognito option

### ISSUE THREAD

**Issue by pokerjk** [FelisCatus/switchysharp#1069]
Hi,

Is it possible to only enable the proxy in incognito and use a direct connection in normal mode?

Thanks,
Jamie

**Comment by FelisCatus** [comment]
This project is no longer maintained. The issue has been filed for the 2.x branch under FelisCatus/SwitchyOmega#10 though so feel free to subscribe there.

There is an alternative approach though. You can add a new person in Chrome and install SwitchySharp/SwitchyOmega for that "person". Then you can use that "person" to browse with proxy while keeping direct connection for your initial "person". It also works with Incognito Mode if you open Incognito Mode from THAT person (not your person).

**Comment by pokerjk** [comment]
Perfect, thank you.
